version: "3.8"

services:
    db:
        image: mongo:4.2
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: superuser
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: tower
    
    mongoexpress:
        image: mongo-express
        ports:
        - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: db
            ME_CONFIG_MONGODB_AUTH_DATABASE: tower
            ME_CONFIG_MONGODB_AUTH_USERNAME: superuser
            ME_CONFIG_MONGODB_AUTH_PASSWORD: 1234
            # ME_CONFIG_BASICAUTH_USERNAME: test
            # ME_CONFIG_BASICAUTH_PASSWORD: test
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_MONGODB_ADMINUSERNAME: superuser
            ME_CONFIG_MONGODB_ADMINPASSWORD: 1234

    server:
        image: lego3410/tower-server:latest
        build:
            context: ./server
            dockerfile: ../Dockerfile.server
        restart: unless-stopped
        ports:
        - "3010:3010"
        # labels:
        # - "traefik.docker.network=default"
    
    client:
        image: lego3410/tower-client:latest
        build:
            context: ./client
            dockerfile: ../Dockerfile.client
        restart: unless-stopped
        ports:
        - "80:80"
        - "8080:8080"
        # - "3010:3010"
        # labels:
        # - "traefik.docker.network=default"

    # proxy:
    #     image: traefik:v2.2
    #     restart: always
        